calibration:
  px_per_meter: 50.0
  ref_length_m: 3.0
  ref_point_1:
  - 847
  - 190
  ref_point_2:
  - 1005
  - 186
camera_id: cam01
camera_name: Camera cam01
entry_line:
  p1:
  - 847
  - 190
  p2:
  - 1005
  - 186
exit_line:
  p1:
  - 1023
  - 1011
  p2:
  - 1694
  - 982
roi:
  polygon:
  - - 847
    - 191
  - - 1024
    - 1025
  - - 1699
    - 1028
  - - 1279
    - 419
  - - 1013
    - 215
  - - 979
    - 177
